In [1]:
!pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl 
!pip install torchvision

ERROR: torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
     |████████████████████████████████| 5.9MB 3.8MB/s eta 0:00:01
     |████████████████████████████████| 748.8MB 50kB/s s eta 0:00:01     |█████████████▊                  | 319.8MB 38.8MB/s eta 0:00:12     |███████████████                 | 352.9MB 41.1MB/s eta 0:00:10MB/s eta 0:00:04


In [2]:
import torch
import torch.autograd as autograd 
import torch.nn as nn 
import torch.optim as optim 

torch.manual_seed(123)


In [3]:
v = [1, 2, 3]
print(type(v))
print(v)

<class 'list'>
[1, 2, 3]


In [4]:
v_tensor = torch.Tensor(v)
print(v_tensor)

tensor([1., 2., 3.])


In [5]:
mx = [[10, 20, 30], [40, 50, 60]]
print(mx)

[[10, 20, 30], [40, 50, 60]]


In [6]:
mx_tesnor = torch.Tensor(mx)
print(mx_tesnor)

tensor([[10., 20., 30.],
        [40., 50., 60.]])


In [7]:
mx2 = [[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]
print(mx2)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]


In [8]:
mx2_tensor = torch.Tensor(mx2)
print(mx2_tensor)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [9]:
mx3_tensor = torch.randn((4, 3, 3, 3))
mx3_tensor.shape
print(mx3_tensor)

tensor([[[[ 3.3737e-01, -1.7778e-01, -3.0353e-01],
          [-5.8801e-01,  3.4861e-01,  6.6034e-01],
          [-2.1964e-01, -3.7917e-01,  7.6711e-01]],

         [[-1.1925e+00,  6.9835e-01, -1.4097e+00],
          [ 1.7938e-01,  1.8951e+00,  4.9545e-01],
          [ 2.6920e-01, -7.7020e-02, -1.0205e+00]],

         [[-1.6896e-01,  9.1776e-01,  1.5810e+00],
          [ 1.3010e+00,  1.2753e+00, -2.0095e-01],
          [ 4.9647e-01, -1.5723e+00,  9.6657e-01]]],


        [[[-1.1481e+00, -1.1589e+00,  3.2547e-01],
          [-6.3151e-01, -2.8400e+00, -1.3250e+00],
          [ 1.7843e-01, -2.1338e+00,  1.0524e+00]],

         [[-3.8848e-01, -9.3435e-01, -4.9914e-01],
          [-1.0867e+00,  8.8054e-01,  1.5542e+00],
          [ 6.2662e-01, -1.7549e-01,  9.8284e-02]],

         [[-9.3507e-02,  2.6621e-01, -5.8504e-01],
          [ 8.7684e-01,  1.6221e+00, -1.4779e+00],
          [ 1.1331e+00, -1.2203e+00,  1.3139e+00]]],


        [[[ 1.0533e+00,  1.3881e-01,  2.2473e+00],
          [-8.0

In [10]:
v = [1, 2, 3]
print(type(v))
v_tensor = torch.Tensor(v)
print(v_tensor)
mx = [[10, 20, 30], [40, 50, 60]]
mx_tesnor = torch.Tensor(mx)
print(mx_tesnor)
mx2 = [[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]
mx2_tensor = torch.Tensor(mx2)
print(mx2_tensor)
mx3_tensor = torch.randn((4, 3, 3, 3))
mx3_tensor.shape
print(mx3_tensor)

<class 'list'>
tensor([1., 2., 3.])
tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]])
tensor([[[[-2.7202,  0.5421, -1.1541],
          [ 0.7763, -0.2582, -2.0407],
          [-0.8016, -0.8183, -0.0480]],

         [[ 0.5349,  1.1031,  1.3334],
          [-1.4053, -0.5922, -0.2548],
          [ 1.1517,  0.8138,  0.6532]],

         [[ 0.6557, -1.4056, -1.2743],
          [ 0.4513, -0.2280,  0.9224],
          [ 0.8566,  0.6465,  1.2782]]],


        [[[ 2.5501, -0.3018, -0.6703],
          [-0.6171, -0.8334,  0.5663],
          [ 1.0306, -0.3047,  1.6873]],

         [[ 0.6851,  2.0024, -0.5469],
          [ 1.6014, -0.3016, -0.7074],
          [-0.1465, -0.4943, -1.1766]],

         [[-2.0524,  0.1132,  1.4353],
          [-1.1454, -1.3316,  0.2230],
          [ 0.6463,  0.1538, -0.4452]]],


        [[[ 0.5503,  0.0658,  0.2225],
          [-0.1689, -0.5455,  0.2487],
          [

In [11]:
mx4 = [[[[10, 20, 30, 40, 50], [60, 70, 80, 90, 100], [110, 120, 130, 140, 150], [160, 170, 180, 190, 200]]]]
print(mx4)
mx4_Tensor = torch.Tensor(mx4)
print(mx4_Tensor)

[[[[10, 20, 30, 40, 50], [60, 70, 80, 90, 100], [110, 120, 130, 140, 150], [160, 170, 180, 190, 200]]]]
tensor([[[[ 10.,  20.,  30.,  40.,  50.],
          [ 60.,  70.,  80.,  90., 100.],
          [110., 120., 130., 140., 150.],
          [160., 170., 180., 190., 200.]]]])


In [12]:
mx4Randn.shape
print(mx4Randn.shape)

NameError: name 'mx4Randn' is not defined

In [ ]:
mx4Randn = torch.randn(10, 20, 30, 40, 50)
mx4Randn.shape
print(mx4Randn.shape)
print(mx4Randn)

In [ ]:
v = v_tensor[0]
print(v)

In [ ]:
v1 = v_tensor[1]
print(v1)

In [ ]:
m = (mx4_Tensor[0])
print(m)

In [14]:
m_tensor = torch.randn((6, 3, 28, 28))
print(m_tensor)

tensor([[[[-8.4548e-01,  1.0481e+00,  9.2213e-01,  ...,  1.4561e+00,
            6.6460e-01,  2.3805e+00],
          [-8.9080e-02,  1.7927e-01,  4.6490e-01,  ...,  2.4183e-01,
           -1.5392e+00, -3.5215e-02],
          [-1.2689e+00,  6.5890e-01,  4.9074e-01,  ..., -7.1490e-01,
           -1.1279e+00, -6.2128e-01],
          ...,
          [ 2.4861e-01, -1.1363e+00,  1.8714e+00,  ..., -4.4709e-01,
            1.3153e+00, -1.1690e+00],
          [ 9.6547e-01, -4.4502e-01,  1.9157e-02,  ..., -1.7191e+00,
           -5.4873e-01,  1.5415e-02],
          [-3.5682e-01, -1.4155e+00, -1.1469e+00,  ..., -1.4771e+00,
            4.4270e-01, -5.8072e-01]],

         [[-8.4435e-01,  3.9567e-01, -3.1204e-01,  ..., -3.3997e-01,
            7.5383e-01, -2.1446e+00],
          [ 2.2980e+00, -9.1292e-02,  9.6210e-01,  ..., -1.8117e-01,
           -1.3202e+00, -1.1225e-02],
          [ 2.1616e-01,  9.3441e-02, -4.9832e-01,  ..., -9.2589e-01,
           -1.4909e-01,  5.3121e-01],
          ...,
     

In [15]:
m_tensor = torch.randn((5, 4, 4, 4))
m_tensor[0]

tensor([[[-0.6022,  1.1448, -1.2100,  0.7550],
         [-0.8736,  1.0299, -0.2774,  1.1761],
         [ 1.7400,  0.0871, -0.7604, -0.1946],
         [ 1.4565,  0.0183,  0.4990,  0.9312]],

        [[-0.5974,  0.9879,  0.8808, -0.5737],
         [ 0.5387,  0.6455, -1.3289,  2.3954],
         [ 1.1456, -0.2786, -0.9653,  0.5780],
         [-0.5297, -0.4778, -1.7308,  0.5774]],

        [[-0.5474,  1.1036, -0.5873, -1.5756],
         [ 0.7006,  0.9885, -0.3619,  0.5669],
         [ 1.0573,  2.6571, -0.8692, -1.6572],
         [-1.0871, -0.7179, -1.3324, -1.1169]],

        [[-1.9410,  2.1953,  1.8257,  0.4922],
         [-0.3827,  0.5720,  0.9850,  1.0534],
         [-0.1647,  1.5200,  0.1877,  0.6097],
         [-0.2396,  1.2822,  0.1343, -0.5494]]])

In [16]:
x = torch.randn(4, 3)
y = torch.randn(3, 4)

In [18]:
z = torch.cat([x, y], 1)
print(z)

RuntimeError: Sizes of tensors must match except in dimension 1. Got 4 and 3 in dimension 0 (The offending index is 1)