In [1]:
!pip install tensorflow==1.3.0

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'1.3.0'

In [4]:
import numpy as np 

In [5]:
a = tf.constant(np.array([1.,2.,3.]))
type(a)

tensorflow.python.framework.ops.Tensor

In [6]:
b = tf.constant(np.array([4.,5.,6.]))
type(b)

tensorflow.python.framework.ops.Tensor

In [7]:
c = tf.tensordot(a,b,1)
type(c)

tensorflow.python.framework.ops.Tensor

In [8]:
S = tf.Session()
output = S.run(c)
print(output)

32.0


In [1]:
!pip install tensorflow==2.0.0-alpha0

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.0.0-alpha0'

In [4]:
import numpy as np 

In [5]:
a = tf.constant(np.array([1.,2.,3.]))
type(a)

tensorflow.python.framework.ops.EagerTensor

In [6]:
a = tf.constant(np.array([1.,2.,3.]))
type(a)
print(a.numpy())

[1. 2. 3.]


In [7]:
b = tf.constant(np.array([4.,5.,6.]))
type(b)

tensorflow.python.framework.ops.EagerTensor

In [8]:
b = tf.constant(np.array([4.,5.,6.]))
type(b)
print(a.numpy())

[1. 2. 3.]


In [9]:
c = tf.tensordot(a,b,1)
type(c)

tensorflow.python.framework.ops.EagerTensor

In [10]:
c = tf.tensordot(a,b,1)
type(c)
print(a.numpy())

[1. 2. 3.]


In [21]:
S = tf.Session()
output = S.run(c)
print(output)

32.0
